### ISSUE TITLE
The nooby bot always play the same moves

### ISSUE THREAD

**Issue by MrMystery10-del** [MrMystery10-del/ChessEngine#11]
Nooby play same moves becaus eit start from left to right and then to the buttom to check all possible moves, when there is a move which could hit something then he plays thsi move but if not he just play the first possibel move which is in the left top corner, to fix it you could randomly sort the given list of possibel moves and only after that comparer for the highest value which can get hit

**Comment by Badrri-Narayanan** [comment]
Hi, can you please assign me this issue?

**Comment by MrMystery10-del** [comment]
Fixed it

**Comment by Badrri-Narayanan** [comment]
@MrMystery10-del sorry I was busy with my work work
