### ISSUE TITLE
Implementation of Choose Ai screen

### ISSUE THREAD

**Issue by MrMystery10-del** [MrMystery10-del/ChessEngine#26]
A screen where you can scroll between different AIs, AIs shoulds be displayed as a picture of it with the name under, shoudl be clickable

**Comment by ShadowOfPixels** [comment]
Can you assign this to me @MrMystery10-del

**Comment by MrMystery10-del** [comment]
Im going to take that

**Comment by MrMystery10-del** [comment]
Not going to take that since the possible fx migrate now
