### ISSUE TITLE
Implementation of Profile Screen

### ISSUE THREAD

**Issue by MrMystery10-del** [MrMystery10-del/ChessEngine#27]
That screen should display the picture of teh user, hes data like name and elo

**Comment by jorn-fa** [comment]
Mind if i grab this one, it will seperate the tasks some more.     Data persisted by file i would assume ?

**Comment by MrMystery10-del** [comment]
Yeah since we only do ai as opponents we will save the data in a file, if we really add muliplayer later then it will work based on sql so try not to hard code it just in case

**Comment by MrMystery10-del** [comment]
Closing because of FX refactor
