### ISSUE TITLE
Implementation of Ava bot with around 500 elo

### ISSUE THREAD

**Issue by MrMystery10-del** [MrMystery10-del/ChessEngine#29]
The algorithm you can decide self which one you choose, keep in mind hat every bot should be kinda unique so try to use algoritms which we not used in other Bots(Bob)

**Comment by MrMystery10-del** [comment]
Also look how Bob work and implement the Bot interface

**Comment by Badrri-Narayanan** [comment]
Hi @MrMystery10-del , can you please assign me this issue?

**Comment by MrMystery10-del** [comment]
Done!

**Comment by MrMystery10-del** [comment]
Any progress? @Badrri-Narayanan 
Do you need help or have questions?

**Comment by MrMystery10-del** [comment]
Since Badri not have time because of his job, soemone else can take that issue

**Comment by MrMystery10-del** [comment]
Implemented
