### ISSUE TITLE
Board is showing possible moves when there are no pieces or no game has started

### ISSUE THREAD

**Issue by jorn-fa** [MrMystery10-del/ChessEngine#45]

**Comment by MrMystery10-del** [comment]
Well i not tested but even if its a bug, when we add the choose Ai screen the user will directly be redirected to teh started game board so that should not be a issue

**Comment by jorn-fa** [comment]
black knights also go upwards instead of down on the list of possible moves

**Comment by MrMystery10-del** [comment]
In chess knights can go in any direction, if thats what u mean

**Comment by jorn-fa** [comment]
no  at the current playboard, click the top black knights.  Moves are not drawn downwards toward the white pieces 

placed at a correct position for capture ->  https://i.imgur.com/JnYgzkZ.png
click on pawns on top shows a valid move ( somethimes )-> https://i.imgur.com/IuGKj5M.png
however:
black knight selection on top row -> https://i.imgur.com/ufNOzrp.png      ( no valid move showing )
